### ISSUE TITLE
Ar fi nevoie de un buton de resetare filtre

### ISSUE THREAD

**Issue by robintel** [gov-ithub/servicii-sociale#20]
### Expected behavior

Pentru că utilizatorilor s-ar putea să nu le fie clar ce servicii anume sunt disponibile în județ, s-ar putea să modifice filtrele. Pentru ușurința utilizării, cred că ar fi util și un buton de reset al filtrelor.

### Actual behavior

Doar reîncărcarea paginii resetează filtrele.

### Steps to reproduce the problem.

1. Selectează județul.
2. Selectează tipul serviciului.
3. Selectează forma de organizare a serviciului.
4. Schimbă tipul serviciului.

### Specifications
version of the project:  public beta of 12th of December 2016

**Comment by cezarneaga** [comment]
Ar mai exista un fel de a reseta filtrele, dar nu e foarte intuitiv. daca selectezi Alba si apoi selectezi Judet se reseteaza.
