### ISSUE TITLE
Aplicația nu funcționează pe IE11

### ISSUE THREAD

**Issue by robintel** [gov-ithub/servicii-sociale#33]
### Expected behavior

Aplicația ar trebui să funcționeze pe toate browserele mainstream.

### Actual behavior

HTML1300: Navigation occurred.
File: harta-furnizori.mmuncii.ro
TypeError: Object doesn't support property or method 'find'
   {
      [functions]: ,
      __proto__: { },
      description: "Object doesn't support property or method 'find'",
      message: "Object doesn't support property or method 'find'",
      name: "TypeError",
      number: -2146827850,
      stack: "TypeError: Object doesn't support property or method 'find'
   at Anonymous function (http://harta-furnizori.mmuncii.ro/static/js/main.d82c3247.js:20:11497)
   at Anonymous function (http://harta-furnizori.mmuncii.ro/static/js/main.d82c3247.js:20:11462)
   at i (http://harta-furnizori.mmuncii.ro/static/js/main.d82c3247.js:15:18277)
   at Anonymous function (http://harta-furnizori.mmuncii.ro/static/js/main.d82c3247.js:15:19021)
   at r (http://harta-furnizori.mmuncii.ro/static/js/main.d82c3247.js:20:885)"
   }

### Steps to reproduce the problem.

1. Open IE11.
2. Navigate to Harta Serviciilor Sociale.
3. Notice how hothing productive seems to happen.

### Specifications
version of the project:  Public Beta, 15/12/2016
operating system:  Windows 6.3.9600 (Windows 8.1 Enterprise)
IE version:  11.0.9600.18525
node version:  
[Eroare incarcare Harta Serviciilor Sociale.docx](https://github.com/gov-ithub/servicii-sociale/files/654239/Eroare.incarcare.Harta.Serviciilor.Sociale.docx)

**Comment by cezarneaga** [comment]
nu merge nici din word. pls dropbox sau altundeva online

**Comment by robintel** [comment]
Uite aici: http://s.go.ro/ejz9o1rg

**Comment by cezarneaga** [comment]
mda. vazut. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find 
metoda .find a aparut de la ie12 in coace pe la MSFT.

**Comment by cezarneaga** [comment]
@MariusGarbea ai putea sa incerci sa rezolvi tu asta ca esti pe stack windows?

**Comment by MariusGarbea** [comment]
@cezarneaga sigur. acum ma apuc

**Comment by cezarneaga** [comment]
Excelent. Merci

**Comment by robintel** [comment]
@cezarneaga IE12? Sau te referi la Edge?

**Comment by cezarneaga** [comment]
nu ma pricep, dar din cate inteleg eu IE12 === edge

**Comment by cezarneaga** [comment]
@MariusGarbea ceva updates?

**Comment by MariusGarbea** [comment]
@cezarneaga am prototipat metoda find si am scapat de eroarea din issue dar mai e ceva pe langa: Error: Unspecified error, din cauza careia banuiesc ca nu randeaza mai departe. Inca sunt in cautare de solutii dar acum inteleg de ce IE sucks. O sa intreb si pe slack ca poate are cineva experienta cu IE.

**Comment by cezarneaga** [comment]
mda. aici am ajuns si eu. bagasem polyfill.io, babel-polyfill, etc.
dar minunea aia de unspecified error nu i-am dat de cap. 

mai ai si alte idei?

**Comment by MariusGarbea** [comment]
momentan doar sa tai din cod si sa vad unde pica. ma gandesc ca ar putea fi de la vreun module care nu e suportat de IE. o sa ma joc putin si vad daca imi iese ceva

**Comment by danmana** [comment]
Nu sunt familiar cu aplicatia si librariile folosite, asa ca nu stiu ce tip este `data.ss`, dar eroarea vine din
[App.js:96](https://github.com/gov-ithub/servicii-sociale/blob/master/src/App.js#L96)

Daca `data.ss` e doar un Object, cum suspectez, atunci IE11 nu suporta metoda .find ... ar trebui folosit ori un for clasic, ori ceva gen [Lodash.find](https://lodash.com/docs/4.17.2#find)

**Comment by cezarneaga** [comment]
Am bagat polyfill si ramane o eroare: unknown error :)

**Comment by danmana** [comment]
@cezarneaga  Aha, am vazut si eu acum

"Unspecified error" pare sa vina din [react CSSPropertyOperations.js#L223](https://github.com/facebook/react/blob/master/src/renderers/dom/shared/CSSPropertyOperations.js#L223) 
`style[styleName] = styleValue;`

cand incearca sa seteze pe un nod `<span style="width: 0px; height: 0px;"></span>` un style cu `styleName = 'content'` si `styleValue = '-'`. 

Nu sunt familiar cu react si nu ma descurc sa imi dau seama unde in codul nostru incercam sa setam content pe span, poate reusesti tu :)

Ca sa te ajute la debugging poti scrie in `./node_modules/react-dom/lib/CSSPropertyOperations.js` inainte de `style[styleName] = styleValue;` ceva de genu: 
```
if (styleName === 'content') {
  debugger;
}
```
Cu developer tools deschis, ar trebui sa se opreasca in breakpoint si sa poti sa te uiti pe stacktrace, poate reusesti sa iti dai tu seama de unde vine ...

**Comment by cezarneaga** [comment]
Merci. E un nou lead. @mariusgarbea hai sa incercam si pe leadul asta. Ma uit si eu dupamasa.

**Comment by MariusGarbea** [comment]
da, ma ocup azi mai pe seara sau maine

**Comment by MariusGarbea** [comment]
am incercat dar nu am ajuns nicaieri. ti-a iesit ceva pana acum @cezarneaga ?

**Comment by cezarneaga** [comment]
ai incercat cumva sa schimbi spans in divs. cica IE se comporta ciudat la asta.

**Comment by MariusGarbea** [comment]
da, nu e de la spans

**Comment by cezarneaga** [comment]
@MariusGarbea ai incercat asta in index: <meta http-equiv="X-UA-Compatible" content="IE=edge">

**Comment by MariusGarbea** [comment]
acelasi rezultat :(

**Comment by ionut-ai** [comment]
Am investigat si eu putin problema. Subscriu la ce a spus @danmana in sensul ca nu ar trebui sa se foloseasca CSS 'content' pe un span. Conform specificatiilor 'content' se foloseste la pseud-elemente ":before"/":after" deci nici un exista un nod in DOM pentru el. Drept pentru care nici nu ar trebui folosit in JS. Ca o traducere la eroarea din IE, ar trebui sa cititi asa: "Unspecified error" = "Atributul 'content' nu se regaseste in specificatiile pentru atributele CSS pentru span (Unspecified), drept pentru care nu se poate seta aceasta proprietate (error).". 
In cazul de fata nu se seteaza manual ci de catre o librarie externa.

Din ce am observat problemele vin de la libraria Belle(din pacate nici pagina lor principala nu merge in IE11 asa ca nu sunt foarte convins de compatibilitatea oferita) care e folosita la filtre (src/components/Sidebar/index.js - Select/Option) . Am facut cateva teste si, daca nu se mai foloseste Belle, si in schimb se foloseste Material UI pentru controalele de acolo (inlocuind Select cu SelectField) se rezolva problema si functioneaza si pe IE11.

**Comment by cezarneaga** [comment]
mda. am rezolvat-o. am forkuit si modificat belle in cateva locuri si merge. acum tre sa astept pana la intoarcere in bucuresti sa pot face push pe production :)
